[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
    "google-cloud-storage>=3.4.0",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.1.1",
]
